version: '3'

networks:
    internal: 
    

services: 
    php:
        build: 
            context: ./config/php
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./www:/var/www/html
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
        ports: 
            - "8000:80"
        networks: 
            - internal
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        command: --innodb_use_native_aio=0
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        # Задаем пароль для root пользователя
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - internal
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
        networks:
            - internal
